---

plugins:
# https://github.com/babel/eslint-plugin-babel
  - babel

#https://eslint.org/docs/user-guide/cofiguring#specifying-environments
env:
  node: true
  browser: true

# https://github.com/babel/babel-eslint
parser:  babel-eslint

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  arrow-parens: ["error", "as-needed"]
